FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /work

COPY *.csproj ./

RUN dotnet restore /work/LoanMS.csproj

COPY . .

FROM build AS publish
WORKDIR /work/
RUN dotnet publish -c Release -o /app --no-restore


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
COPY --from=publish /app .


ENTRYPOINT ["dotnet", "LoanMS.dll"]
